matcher:
  KDTreeMatcher:
    maxDist: 0.9
    knn: 3
    epsilon: 3.16

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.90
  - SurfaceNormalOutlierFilter:
     maxAngle: 0.42

errorMinimizer:
  PointToPlaneErrorMinimizer
#  PointToPlaneWithCovErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 0.80
      maxTranslationNorm: 5.00

inspector:
  #PerformanceInspector:
  #VTKFileInspector:
    #dumpPerfOnExit: 1
    #dumpStats: 1
  NullInspector

logger:
  FileLogger:
    infoFileName: info.log
    warningFileName: warn.log
    displayLocation: 1
